### ISSUE TITLE
Question: Backend server

### ISSUE THREAD

**Issue by homam** [didierfranc/redux-react-starter#4]
I guess it is a general question about best practices:

There's a reference to a backend API server in [urls.js](https://github.com/didierfranc/redux-react-starter/blob/master/src/constants/urls.js#L1). Where is the code for this server?

Do you think that this starter kit should also show-case handling of booth backend and front-end code in the same repo? Particularly in production, because of the payment model of services like Heroku.

**Comment by didierfranc** [comment]
The backend used for the live example is very simple. It's just some lines of javascript : **express + jsonwebtoken**. I'll make it clean enough to share it ([probably a gist](https://gist.github.com/didierfranc/bb9a41f0d745a5a84dd0f798b9acd4d5) to let this repo pure client oriented). If you're hurry take a look [here](https://medium.com/@rajaraodv/securing-react-redux-apps-with-jwt-tokens-fcfe81356ea0) ;)
