### ISSUE TITLE
Great starter but I am bad with css, help needed.

### ISSUE THREAD

**Issue by rolele** [didierfranc/redux-react-starter#6]
Hi,
thanks for this starter I think it is great.
I see that you are using styled-component which is great.
My problem is that I have no talent with css so I try to use libraries like bootstrap.

The only problem is that I would like to still use css-module and only bundle the css that I actually use in my app. Also doing chuncking on the css.
I do not think this is possible with react-bootstrap. I think you include bootstrap globaly and your component className attr will be plain string.

I guess there is many way to do it I just can not find an efficient one.
I guess my question is: 
How to integrate bootstrap to your starter in an efficient manner (because I am terrible with css)?

**Comment by didierfranc** [comment]
I just tested the following guide https://react-bootstrap.github.io/getting-started.html and everything is fine 😉
