### ISSUE TITLE
App not working / npm start

### ISSUE THREAD

**Issue by kamalkech** [didierfranc/redux-react-starter#7]
node : v6.10.0
npm : 3.10.10

λ npm start

> redux-react-starter@1.0.0 start C:\Projets\React\redux-react-starter
> tsc && concurrently "npm run tsc:w" "npm run web" "npm run rest"

typings/modules/react-dom/index.d.ts(165,11): error TS2559: Type 'Component<P, S>' has no properties in common with type 'ComponentLifecycle<P, S>'.
typings/modules/react/index.d.ts(165,11): error TS2559: Type 'Component<P, S>' has no properties in common with type 'ComponentLifecycle<P, S>'.

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! redux-react-starter@1.0.0 start: `tsc && concurrently "npm run tsc:w" "npm run web" "npm run rest" `
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the redux-react-starter@1.0.0 start script 'tsc && concurrently "npm run tsc:w" "npm run web" "npm run rest" '.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the redux-react-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc && concurrently "npm run tsc:w" "npm run web" "npm run rest"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs redux-react-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls redux-react-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Projets\React\redux-react-starter\npm-debug.log

**Comment by venkateshtl** [comment]
Hi, did you get the fix? Even I have the same issue.

**Comment by venkateshtl** [comment]
Hi, did you get the fix? Even I have the same issue.

**Comment by kamalkech** [comment]
@venkateshtl  : Nop, i remove it and i start from scratch with create-react-app

**Comment by didierfranc** [comment]
I'm not a Window user but I can see some things that can cause issues:

- You're using it as a package and it's not the purpose
- Node version
- Yarn vs npm
- Typescript

**Comment by kamalkech** [comment]
@didierfranc i have this : 
node -v : v6.11.2
npm -v : 5.3.0
tsc -v : Version 2.2.1 

so i have a last versions.

**Comment by eaotnc** [comment]
I use npm install it can't started. but use yarn install it work.
